package com.example.examplemod;

import com.mojang.logging.LogUtils;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.item.Item;
import net.minecraftforge.event.server.ServerStartingEvent;
import net.minecraftforge.fml.ModLoadingContext;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.config.ModConfig;
import net.minecraftforge.fml.event.lifecycle.FMLCommonSetupEvent;
import net.minecraftforge.fml.javafmlmod.FMLJavaModLoadingContext;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.ForgeRegistries;
import org.slf4j.Logger;
import net.minecraftforge.eventbus.api.IEventBus;
import net.minecraftforge.eventbus.api.SubscribeEvent;
import net.minecraftforge.common.MinecraftForge;
import net.minecraft.world.entity.LivingEntity;
import net.minecraft.network.chat.Component;
import net.minecraftforge.event.entity.EntityJoinLevelEvent;
import java.util.Map;
import java.util.HashMap;
import net.minecraft.world.entity.EntityType;

// The value here should match an entry in the META-INF/mods.toml file
@Mod(ExampleMod.MODID)
public class ExampleMod
{
    // Define mod id in a common place for everything to reference
    public static final String MODID = "examplemod";
    // Directly reference a slf4j logger
    private static final Logger LOGGER = LogUtils.getLogger();
    // Create a Deferred Register to hold Blocks which will all be registered under the "examplemod" namespace
    public static final DeferredRegister<Block> BLOCKS = DeferredRegister.create(ForgeRegistries.BLOCKS, MODID);
    // Create a Deferred Register to hold Items which will all be registered under the "examplemod" namespace
    public static final DeferredRegister<Item> ITEMS = DeferredRegister.create(ForgeRegistries.ITEMS, MODID);
    // Add this near your other static fields
    private static final Map<EntityType<?>, String[]> MOB_NAMES = new HashMap<>();

    public ExampleMod()
    {
        IEventBus modEventBus = FMLJavaModLoadingContext.get().getModEventBus();

        // Register the commonSetup method for modloading
        modEventBus.addListener(this::commonSetup);

        // Register the Deferred Register to the mod event bus so blocks get registered
        BLOCKS.register(modEventBus);
        // Register the Deferred Register to the mod event bus so items get registered
        ITEMS.register(modEventBus);

        // Register ourselves for server and other game events we are interested in
        MinecraftForge.EVENT_BUS.register(this);

        // Register our mod's ForgeConfigSpec so that Forge can create and load the config file for us
        ModLoadingContext.get().registerConfig(ModConfig.Type.COMMON, Config.SPEC);

        // Add this in your constructor
        initializeMobNames();
    }

    private void commonSetup(final FMLCommonSetupEvent event)
    {
        // Some common setup code
        LOGGER.info("HELLO FROM COMMON SETUP");
    }

    @SubscribeEvent
    public void onServerStarting(ServerStartingEvent event)
    {
        // Do something when the server starts
        LOGGER.info("HELLO from server starting");
    }

    @SubscribeEvent
    public void onEntitySpawn(EntityJoinLevelEvent event) {
        if (event.getLevel().isClientSide()) return;
        if (!(event.getEntity() instanceof LivingEntity living)) return;
        
        String[] possibleNames = MOB_NAMES.get(living.getType());
        if (possibleNames != null && event.getEntity().getCustomName() == null && Math.random() < 0.001f) {
            String randomName = possibleNames[(int)(Math.random() * possibleNames.length)];
            living.setCustomName(Component.literal(randomName));
            living.setCustomNameVisible(true);
        }
    }

    private void initializeMobNames() {
        MOB_NAMES.put(EntityType.ALLAY, new String[]{"Echo", "Whisper", "Chime", "Seraph", "Faye", "Sylph", "Harmonia", "Lira", "Auralis", "Vesper", "Cadenza", "Bellora", "Tremor", "Flare", "Zephyr", "Cadence", "Aether", "Lumen", "Sonata", "Melody", "Aria", "Chorus", "Aura", "Chimeleaf", "Symphony", "Elysia"});
        MOB_NAMES.put(EntityType.AXOLOTL, new String[]{"Ripple", "Coral", "Glimmer", "Marina", "Aqua", "Tide", "Current", "Splash", "Lagoon", "Cascade", "Oasis", "Misty", "Fluoro", "Bubbles", "Pebble", "Waves", "Tidal", "Azure", "Shimmer", "Cobalt", "Surge", "Breeze", "Aquilo", "Reef", "Siren", "Nimbus"});
        MOB_NAMES.put(EntityType.ARMOR_STAND, new String[]{"Sentinel", "Guard", "Vanguard", "Ward", "Protector", "Sentinel-X", "Aegis", "Defender", "Watchman", "Palisade", "Ironclad", "Fortis", "Bastion", "Shieldbearer", "Outpost", "Rampart", "Helm", "Armatus", "Warden", "Talon", "Elder", "Citadel", "Sentinel Prime", "Guardian", "Valor", "Titus"});
        MOB_NAMES.put(EntityType.BAT, new String[]{"Echo", "Shadow", "Nocturne", "Velvet", "Whisper", "Vesper", "Wraith", "Phantom", "Nimbus", "Midnight", "Specter", "Swoop", "Gloom", "Havoc", "Shade", "Flit", "Shadewing", "Dusk", "Ebon", "Cavern", "Lurker", "Flutter", "Twilight", "Banshee", "Vapor"});
        MOB_NAMES.put(EntityType.BEE, new String[]{"Buzz", "Pollen", "Honey", "Nectar", "Amber", "Sting", "Lilac", "Dewdrop", "Sweets", "Bumble", "Flora", "Pollinate", "Bloom", "Meadow", "Hive", "Petal", "Golden", "Dandelion", "Amberly", "Wingnut", "Thyme", "Clove", "Blossom", "Clover", "Royalty", "Syrup"});
        MOB_NAMES.put(EntityType.BLAZE, new String[]{"Ember", "Inferno", "Scorch", "Cinder", "Flare", "Pyra", "Vulcan", "Ignite", "Ashen", "Sear", "Torch", "Blazeheart", "Fury", "Flamewing", "Smolder", "Char", "Eruption", "Wildfire", "Scald", "Burnstrike", "Heatwave", "Crimson", "Blazingstar", "Lavaflare", "Firestorm", "Sizzle"});
        MOB_NAMES.put(EntityType.BOAT, new String[]{"Drift", "Voyager", "Crest", "Sailor", "Tide", "Nautica", "Seabreeze", "Oar", "Mariner", "Waveskip", "Current", "Navigator", "Lifeboat", "Rudder", "Seaway", "Adrift", "Skiff", "Oasis", "Shoreside", "Clipper", "Harbor", "Windward", "Seafarer", "Aquatic", "Breezeway", "Anchor"});
        MOB_NAMES.put(EntityType.CAMEL, new String[]{"Dusty", "Sahara", "Oasis", "Humpfree", "Sirocco", "Sandstride", "Dune", "Caravan", "Nomad", "Desertwind", "Arid", "Sandy", "Mirage", "Cinder", "Sol", "Parcher", "Khamsin", "Goldenhoof", "Trailblazer", "Harir", "Cactus", "Sunstride", "Balthazar", "Sandstorm", "Dromedary", "Shadewalker"});
        MOB_NAMES.put(EntityType.CAT, new String[]{"Whiskers", "Shadow", "Mittens", "Luna", "Felix", "Pounce", "Midnight", "Tux", "Socks", "Cleo", "Salem", "Tiger", "Patches", "Mochi", "Snowball", "Onyx", "Marble", "Tabby", "Ash", "Simba", "Pumpkin", "Sable", "Pearl", "Jinx", "Cheshire", "Silky"});
        MOB_NAMES.put(EntityType.CHICKEN, new String[]{"Cluckers", "Feathers", "Eggbert", "Henrietta", "Pip", "Rooster", "Peep", "Fluffy", "Sunny", "Scramble", "Bantam", "Chirpy", "Frieda", "Talon", "Poultry", "Cackle", "Breezy", "Drumstick", "Sunny", "Penny", "Fluff", "Cocoa", "Chirrup", "Beak", "Plum"});
        MOB_NAMES.put(EntityType.COW, new String[]{"MooMoo", "Daisy", "Bessie", "Buttercup", "Angus", "Spot", "Clover", "Patch", "Milkshake", "Brownie", "Oreo", "Holstein", "Mooella", "Grasshopper", "Tinker", "Moosifer", "Bella", "Choco", "Hoofheart", "Hazel", "Maple", "Myrtle", "Moomint", "Ivory", "Fudge", "Poppy"});
        MOB_NAMES.put(EntityType.CREEPER, new String[]{"Boomer", "Fuse", "Kablooey", "Nitro", "Blastbite", "Volto", "Shocker", "Detona", "Sizzle", "Splodey", "Crater", "Spark", "Bangtail", "Creeptor", "Kablam", "TNT", "Frag", "Blitz", "Puff", "Ignis", "Zapper", "Stalker", "Cinder", "Ashbang", "Kaboom", "Fizzler"});
        MOB_NAMES.put(EntityType.CAVE_SPIDER, new String[]{"Venom", "Silkfang", "Webber", "Skitter", "Nightbite", "Toxica", "Arachnis", "Fangshade", "Cavernclaw", "Widow", "Spinner", "Venoma", "Spindle", "Duskrunner", "Webfang", "Noctura", "Chasmweaver", "Poisonclaw", "Cobble", "Ebonfang", "Darkthread", "Venospin", "Tunnelfang", "Silkraider", "Webmistress"});
        MOB_NAMES.put(EntityType.COD, new String[]{"Bubbles", "Finn", "Ripple", "Gill", "Swimmy", "Marina", "Waver", "Drift", "Scales", "Aqua", "Splash", "Nibbler", "Dart", "Skipper", "Tidbit", "Current", "Flipper", "Stream", "Wavelet", "Minnow", "Brookie", "Spritz", "Flow", "Lure", "Guppy", "Coral"});
        MOB_NAMES.put(EntityType.DOLPHIN, new String[]{"Flipper", "Echo", "Splash", "Ariel", "Marina", "Dart", "Wave", "Finn", "Aqua", "Coral", "Bubbles", "Skipper", "Blu", "Tide", "Ripple", "Cascade", "Seabreeze", "Luna", "Current", "Dory", "Azure", "Harbor", "Seaswift", "Glide", "Nimbus", "Crest"});
        MOB_NAMES.put(EntityType.DONKEY, new String[]{"Bray", "Mule", "Dusty", "Toby", "Gizmo", "Clover", "Jasper", "Pippin", "Rusty", "Trott", "Scout", "Dusty", "Ranger", "Buck", "Galahad", "Whisker", "Boulder", "Tango", "Maverick", "Jack", "Saddle", "Boots", "Echo", "Jolly", "Corky", "Copper"});
        MOB_NAMES.put(EntityType.DROWNED, new String[]{"Marrow", "Undertow", "Soggy", "Brine", "Wraithwater", "Abyss", "Murkwalker", "Tidebane", "Rotfin", "Ebb", "Saltshade", "Crestfallen", "Fathom", "Dredge", "Seablight", "Shipwreck", "Kelper", "Undercurrent", "Lurch", "Coralrot", "Barnacle", "Waterscourge", "Riptide", "Sunk", "Gravecurrent", "Aquagloom"});
        MOB_NAMES.put(EntityType.ENDER_DRAGON, new String[]{"Lord Fluffernutter of the Endless Void, Eater of Ender Pearls and Destroyer of All Common Sense", "The Majestic Winged Overlord of Interdimensional Chaos, Defender of the Ender Realm and Snack Enthusiast", "Professor Scales McFang, the Unstoppable Wielder of Dark Magic, Conqueror of Small Villages and Distant Lands", "Queen Shadowfluff the Untamable, Mistress of the End and Unrivaled Champion of Pixelated Destruction", "Her Royal Highness, Lady Whiskers of the Obliterated Sky, Destroyer of Blocks and Master of the Ender Dimension", "Baron Von Flamebreath, Lord of the Endless Abyss and Collector of Extremely Unnecessary Items", "Sir Flaps-a-lot, the Fearsome Fiery Ender Dragon of Infinite Night and Unlikely Hero of the End Portal", "The Rightful Sovereign of the Blackened Skies, Winged Monarch of Darkness and Overeater of Ender Crystals", "Drakenshard the Uncontrollable, Devourer of Worlds and Champion of Endless Mid-Air Shenanigans", "The One and Only Ender Tater Tot of the Infinite Horizon, Wielder of Fire, Lightning, and Extremely Confusing Powers"});
        MOB_NAMES.put(EntityType.ENDERMAN, new String[]{"Shade", "Echo", "Obsidian", "Voidwalker", "Erebus", "Phantom", "Noctis", "Gloom", "Silhouette", "Specter", "Twilight", "Whisper", "Ender", "Eclipse", "Abyss", "Wraith", "Nightshade", "Lucid", "Dusk", "Cloak", "Rift", "Darkling", "Hollow", "Umbra", "Pale", "Xerath"});
        MOB_NAMES.put(EntityType.ENDERMITE, new String[]{"Flicker", "Scurry", "Shiver", "Vex", "Phantomite", "Wisp", "Dart", "Spindle", "Fume", "Grim", "Chitter", "Blink", "Twitch", "Flick", "Wander", "Voidling", "Gnash", "Fracture", "Spiral", "Riftmite", "Slink", "Shard", "Glitch", "Tear", "Vanish", "Creep"});
        MOB_NAMES.put(EntityType.ELDER_GUARDIAN, new String[]{"Emperor Spikyflop the Oceanic Overlord, Master of the Deep Sea, and Provider of Unwanted Pain", "Lord Tidalwave the Abyssal, Keeper of the Oceans Secrets and Unapologetic Stinger of Everything", "Queen Tentacledom the Imposing, Ruler of the Oceanic Depths and Defiler of Your Peaceful Swimming Experience", "The Unbeatable Baron of the Deep, Conqueror of Seafloor Realms and Purveyor of the Worst Spa Experience", "Grandmaster Stingtail the Unyielding, Protector of the Sea and Devourer of All Who Dare Swim Near", "Sir Spineflap the Mysterious, Master of the Oceanic Abyss and Reluctant Guardian of Fishy Things", "The Great Krakenlord of the Deepest Depths, Terror of the Waterways, and Collector of Not-So-Friendly Pets", "High Chancellor Painfin the Ancient, Guardian of the Sea and Chronic Botherer of Boat-Riders Everywhere", "The Overbearing Shimmerfin, First of His Name, Lord of the Underwater Kingdom and Professional Drown-Inducer", "Titanic Stingscale the Eternal, Overseer of Oceanic Menace and Stealthy Destroyer of Underwater Hopes"});
        MOB_NAMES.put(EntityType.EVOKER, new String[]{"Hex", "Rune", "Voldar", "Malachi", "Sorath", "Wraithbinder", "Vesper", "Aldric", "Grimward", "Elderhex", "Fangorn", "Zephar", "Varkoth", "Corvus", "Eldritch", "Runebinder", "Mystic", "Thorn", "Obsidian", "Vilethorn", "Darkroot", "Scorn", "Raven", "Lucian", "Spellbound", "Torin"});
        MOB_NAMES.put(EntityType.FOX, new String[]{"Rustle", "Pip", "Autumn", "Maple", "Ember", "Vixen", "Shadow", "Cedar", "Pounce", "Sable", "Crimson", "Bracken", "Flicker", "Dapple", "Alder", "Bramble", "Frost", "Twilight", "Cinder", "Blaze", "Nox", "Whisker", "Saffron", "Breezy", "Thistle", "Copper"});
        MOB_NAMES.put(EntityType.FROG, new String[]{"Lily", "Hopper", "Swampy", "Ribbit", "Tadpole", "Moss", "Splash", "Jumpy", "Puddle", "Croak", "Boggy", "Pond", "Fern", "Tad", "Kermit", "Mire", "Algae", "Bouncer", "Marsh", "Dew", "Frodo", "Bubbles", "Wart", "Greenleaf", "Dewdrop", "Lurk"});
        MOB_NAMES.put(EntityType.GHAST, new String[]{"Phantom", "Wail", "Banshee", "Screech", "Specter", "Ethereal", "Lament", "Hollow", "Cryos", "Nocturne", "Wraith", "Fury", "Lurker", "Voidcry", "Shiver", "Abyssal", "Sorrow", "Howl", "Grieve", "Blight", "Doom", "Mourn", "Nightshade", "Fright", "Gloom", "Truman"});
        MOB_NAMES.put(EntityType.GLOW_SQUID, new String[]{"Glimmer", "Lumen", "Neon", "Radiant", "Nova", "Shine", "Twilight", "Phosphor", "Aether", "Flare", "Illumine", "Glare", "Glowfish", "Lumina", "Spectra", "Starling", "Pulse", "Eclipse", "Flicker", "Glowmist", "Lustrous", "Halo", "Dawn", "Wisp", "Frostlight", "Celeste"});
        MOB_NAMES.put(EntityType.GOAT, new String[]{"Alpine", "Cliff", "Billy", "Sierra", "Rocky", "Nanny", "Hornet", "Bluff", "Tundra", "Stomp", "Echo", "Frost", "Mountain", "Ramble", "Summit", "Cairn", "Buck", "Hiker", "Snowdrift", "Pebble", "Boulder", "Glacier", "Ridge", "Fjord", "Grit"});
        MOB_NAMES.put(EntityType.GUARDIAN, new String[]{"Sentinel", "Aegis", "Warden", "Proteus", "Obsidian", "Vigil", "Triton", "Seaborn", "Defender", "Aquarius", "Neptune", "Sentinel-X", "Watchman", "Lurker", "Coralguard", "Tidewarden", "Deepstrike", "Abyssal", "Riptide", "Nereus", "Trident", "Fathom", "Kraken", "Mariner", "Seaguard"});
        MOB_NAMES.put(EntityType.HOGLIN, new String[]{"Snorty McSnortface", "Grunty", "Porky Paws", "Baconator", "Wigglebutt", "Hogzilla", "Sir Oinks-a-lot", "Grizzle", "Snuffler", "Hammy", "Piggy Wiggler", "Boar-ito", "Chompers", "Sausage Sam", "Munchy McHog", "Porkchop", "Snuffles", "Tuskles", "Barbecue Billy", "Gruntmaster", "Sizzlepig", "Piggy Stardust", "Swine-dog", "Stompers", "Hammy Hog"});
        MOB_NAMES.put(EntityType.HORSE, new String[]{"Neighsayer", "Gallop McTrotface", "Sir Hoofington", "Mane Event", "Trotty McTrottface", "Whinny the Pooh", "Hoof Hearted", "Clip-clop", "Galloper", "Saddles McPony", "Mister Whinnypants", "Stompy", "Horsie McHorseface", "Canter Man", "Trotter", "Hoofer", "Equine Queen", "Sir Gallopsalot", "Fluffy McTrot", "Mane Man", "Princess Hoof", "Nay-Nay", "Ponyta", "Stirrup", "Clydesdale McSnorts"});
        MOB_NAMES.put(EntityType.HUSK, new String[]{"Crunchy McSandy", "Mummy McMumface", "Sandy Bones", "Gravel Gut", "Dusty McGrim", "Scrawny McSands", "Sandwich", "Gravel Guts", "Bone Dry", "Crispy McCreep", "Sandy McSniffles", "Mummified Fred", "Dusty Dune", "Rattle", "Huskie", "Skeletina", "Sandy McSkele", "The Crumblinator", "Crispy Carl", "Raggedy Ralph", "Bonebreaker", "Scorchy", "Sandy Pants", "Rattlebones", "Dune Dude"});
        MOB_NAMES.put(EntityType.ILLUSIONER, new String[]{"Magical McMimic", "Tricky McTrickster", "Illusio-ninja", "Phantom Phil", "Presto", "Hocus Pocus", "Wizard Wobble", "Mister Mirage", "Abra Cadabra", "Flicker McFoolery", "Illusion Bob", "Mimic Master", "Puff the Pretender", "Sleight-of-Hand Sammy", "Disappearo", "Abracadabra Andy", "Sneaky Pete", "Poof!", "Illusiona", "Professor Puff", "Now You See Me", "Sir Tricksalot", "Ghostly Gus", "Disappearo-doodle", "Sneakster", "Magico"});
        MOB_NAMES.put(EntityType.IRON_GOLEM, new String[]{"Tinny McSmash", "Rusty", "Clankster", "Iron Butt", "Metalhead", "Sir Ironclad", "Golem McJingle", "Rusty Rumble", "Irony", "Smashington", "C-3P0", "Gizmo Golem", "Clanky McStomp", "Boulder Buster", "Platinum Pete", "Titanic Tom", "Tinker Golem", "Steely Dan", "Crunchy", "Chunky McSmash", "Robo-Rumble", "Golemtron", "Tin Can", "Gearhead", "Ironimus Prime"});
        MOB_NAMES.put(EntityType.LLAMA, new String[]{"Alpaca-lips", "Llamageddon", "Spitfire", "Fluffington", "Sir Spitsalot", "Llama Drama", "Tina the Spitter", "Llamacorn", "Chomper", "Fuzzy McLlama", "Llamanator", "Spitzy", "Baa Baa", "Llama Llama", "Hump McFluff", "Llamalicious", "Puffy", "Mister Llama", "Spitty McSpitface", "Whiskers", "Fuzzbucket", "Clopper", "Cactus", "Fluffernutter", "Llamo"});
        MOB_NAMES.put(EntityType.MAGMA_CUBE, new String[]{"Jelly Blobby", "Fluffburn", "Squishy McSizzle", "Pudding Pop", "Melted Marshmallow", "Hot Jelly", "Gooey McMelt", "Lava Pudding", "Jellyfire", "Squishface", "Magma Munch", "Bubbly McBlaze", "Gloop", "Fizzy", "Sizzleblob", "Burny McSquish", "Lava Lump", "Boilington", "Squish Blaze", "Magma Mellow", "Puffball", "Meltface", "Blobber", "Lava Jelly", "Jellybean"});
        MOB_NAMES.put(EntityType.MULE, new String[]{"Donkey Kong", "Muley McMuleface", "Trotty McTrotface", "Sir Muleton", "Mule-ificent", "Burro", "Munchy McMule", "Trots-a-lot", "Bucky", "Muley Poppins", "Clopster", "Moolicious", "Hitch", "Whinny McMule", "Gallopy", "Saddlebags", "Kickstart", "Braylin", "Mule-icious", "Hoofington", "Mr. Trotter", "Mulemeister", "Bootstraps", "Clopper McMule", "Trot McClopperson"});
        MOB_NAMES.put(EntityType.MOOSHROOM, new String[]{"Shroomy McMoo", "Fungi", "Moo-Mush", "Sporey", "Mushroom McMoo", "Cheddar", "Moo-llini", "Sporey McMoo", "Taco Shroom", "Moo-ception", "Fungus Among Us", "Moozilla", "Mushmoo", "Shroomzilla", "Moo-Mushroom", "Shroomerang", "Spory McSpore", "Mushroom McGravy", "Truffle Moo", "Shroomburger", "Puffball", "Spore-tacular", "Moo-Fungi", "Fungus the Great", "Chanterelle"});
        MOB_NAMES.put(EntityType.OCELOT, new String[]{"Whiskers McSneaky", "Pounce-a-lot", "Furrball", "Sir Meows-a-lot", "Leopardini", "Sassy Paws", "Cuddle Pounce", "Kitty McZoom", "Furrtastic", "Fluffernutter", "Sneakster", "Mister Purrfect", "Paws McPounce", "Leopurr", "Jumpy McWhiskers", "Fuzzypaws", "Zoomie", "Purrito", "Meowster", "Clawsome", "Spots McSnuggle", "Snoozer", "Whiskerpounce", "Mochi", "Furball McSqueak"});
        MOB_NAMES.put(EntityType.PANDA, new String[]{"Sir Bamboo", "Panda-monium", "Cuddlepuff", "Munchington", "Bamboozle", "Fluffster", "Chubby McPanda", "Panda-lounger", "Snugglepaws", "Fuzzbucket", "Bamboozled", "Panda Express", "Chunky McChomp", "Crispy", "Wobbles", "Furball", "Panda Pop", "Panda-pocalypse", "Munchy McSnuggles", "Fluffington", "Cuddlebug", "Bamboo Bandit", "Wigglepaws", "Sleepypanda", "Panda-licious"});
        MOB_NAMES.put(EntityType.PARROT, new String[]{"Polly Waddle", "Beak-a-boo", "Squawkzilla", "Flappy McFeathers", "Chirpster", "Sir Squawksalot", "Mango", "Feathery McFlap", "Jolly Jester", "Plumpton", "Squawk-a-lot", "Tweety McTweet", "Macaw-esome", "Fuzzfeather", "Parroty McParrotface", "Captain Cluck", "Tiki", "Pecky", "Wigglebeak", "Pip the Parrot", "Flapjack", "Jungle Jim", "Chirpy McChirp", "Poppins", "Whistle"});
        MOB_NAMES.put(EntityType.PHANTOM, new String[]{"Flappy McScreech", "Boo McScare", "Snoozer", "Wakey McWake", "Spooky McFlap", "Screechy", "Nighty McPhantom", "Flapster", "Phantom PJs", "Ghoulie", "Swoopy", "Spookles", "Flapjack", "Sir Screechalot", "Nightmare Flap", "Snoozy McPhantom", "Boogieman", "Ghastly McFlap", "Sleepy Screamer", "Fright Flight", "Snoozey", "Flapadoodle", "Banshee McFly", "Mummified McFlap", "Sleepypants"});
        MOB_NAMES.put(EntityType.PIG, new String[]{"Oinkster", "Bacon McSnort", "Sir Oinks-a-lot", "Porkchop", "Hammy", "Snouty McSnuffle", "Gruntmaster", "Sizzle", "Piggly Wiggly", "Hogwild", "Porky", "Baconator", "Piggy Stardust", "Moo-Hog", "Snuffles", "Tater Tot", "Trotter", "Hogzilla", "Piglet", "Chomper", "Snorty", "Porkerino", "Bacon Bits", "Hamlet", "Mudbutt"});
        MOB_NAMES.put(EntityType.PIGLIN, new String[]{"Oinklin", "Goldie McSnort", "Gruntz", "Snouty McLoot", "Piggy Stardust", "Goldilocks", "Sir Snorts-a-lot", "Hammy McHog", "Piggy McBling", "Porkchop Prince", "Sniffles", "Goldy McGruntface", "Tusk Trotter", "Bacon Bandit", "Grim Grunt", "Nugget Noser", "Hoggy", "Sizzle Snout", "Oinky McShiny", "Moolah McMoo", "Tuskers", "Boar Barter", "Lootlin", "Swine Shine", "Tusk N' Loot"});
        MOB_NAMES.put(EntityType.PIGLIN_BRUTE, new String[]{"Gruntzilla", "Snorty McSmash", "Bacon Brawler", "Tusk-Tastic", "Grim Grunter", "Boar Buster", "Snouty McSlammer", "Thorny McTusk", "Brawn-O", "Gruntmaster Flex", "Porkchop Pounder", "Smashington", "Hogwild Hulk", "Rage-olin", "Boar-ito", "Snuff the Tough", "Baconator Brawn", "Iron Snout", "Piggy Power", "Brutal Bacon", "Grunty McBrute", "Oinkzilla", "Fury Hog", "Tusk Smash", "Piggy Hulk"});
        MOB_NAMES.put(EntityType.POLAR_BEAR, new String[]{"Fluffy McIce", "Chilly McChomp", "Snowpaws", "Beary McSnuggles", "Frosty the Bearman", "Sir Fluffington", "Icy Paws", "Snowball", "Cuddlebear", "Beary Potter", "Mittens", "Furball McFrost", "Snugglepaws", "Blizzard Buddy", "Chompers", "Waddles", "Cold Snout", "Flurry", "Teddy McTundra", "Mr. Igloo", "Frostbite", "Pawzilla", "Chillax", "Fluffernutter", "Snowy McFluff"});
        MOB_NAMES.put(EntityType.PUFFERFISH, new String[]{"Spiky McPuff", "Bubbles", "Blowfish McSnort", "Puffy McPuffface", "Pufferoni", "Spikester", "Inflato", "Popper", "Fizzy", "Puffzilla", "Mr. Puffles", "Bubble Trouble", "Puffball", "Fluffernator", "Blowey", "Blimp", "Chubster", "Puff Puff", "Fizzy McFish", "Spikey McSwim", "Puff Daddy", "Fluffball", "Puffkins", "Chompers", "Pufferpuff"});
        MOB_NAMES.put(EntityType.RABBIT, new String[]{"Hoppy McSnuggle", "Bunny McBounces", "Flopsy", "Sir Hopsalot", "Carrot King", "Thumper", "Munchkins", "Binky", "Fluffykins", "Hopscotch", "Bunzilla", "Mister Hops", "Cuddlepuff", "Nibbles", "Hopster", "Wabbit", "Twitchy", "Fluffington", "Jumpy McFluff", "Mr. Bunny", "Hopperoni", "Snoozer", "Furball", "Cotton-Tail", "Bunny Butts"});
        MOB_NAMES.put(EntityType.RAVAGER, new String[]{"Smashy McStomp", "Rumblebutt", "Chomperoni", "Crashington", "Ravaging Ralph", "Boulder McBash", "Thudster", "Rumblepaws", "Grumblebeast", "Big Boom", "Tusk-a-lot", "Bashmaster", "Slamzilla", "Thud McTusk", "Hogzilla", "Bam Bam", "Whompster", "Gruntzilla", "Crushington", "Tusked Terror", "Squishmaster", "Boar-nado", "Ravageroni", "Slammy", "Bashington"});
        MOB_NAMES.put(EntityType.SALMON, new String[]{"Swimmy McSplash", "Salmonator", "Bubbly McSwim", "Sizzlefin", "Flippy", "Gilligan", "Swimmy McFishface", "Finny", "Splashy", "Sir Swim-a-lot", "Bubbles", "Salmonella", "Mister Fish", "Salmon Supreme", "Fin-tastic", "Wiggles", "Tidal McTide", "Flickerfin", "Scales", "Gilly", "Captain Swim", "Aquafish", "Bubbly Gill", "Swimster", "Splish"});
        MOB_NAMES.put(EntityType.SHEEP, new String[]{"Fuzzy McFluff", "Baa Baa", "Woolly McWoolface", "Mutton McMoo", "Fluffernutter", "Baa-rbara", "Sheepy McSheepface", "Woollypop", "Snuggles", "Baa-rack Obama", "Cottonball", "Woolster", "Fluffykins", "Puffy", "Lambchop", "Shorn", "Baa-rbecue", "Wooligan", "Shear Delight", "Muttonator", "Fuzzball", "Woolaroo", "Baa-nana", "Fluff-a-lot", "Lamborghini"});
        MOB_NAMES.put(EntityType.SHULKER, new String[]{"Boxy McBoom", "Shell Shock", "Mister Squishy", "Sneaky Box", "Shulky McPop", "Clammy", "Popper", "Boombox", "Shelleton", "Squishy McSquirt", "Hidey McPop", "Box-o'-Boom", "Snugger", "Whisperbox", "Shulkster", "Puffy McHide", "Popperoni", "Shellshock", "Popcorn", "Houdini Box", "Mr. Sneaky", "Bam Box", "Shulky Puff", "Turtley", "Boomy McBoxface"});
        MOB_NAMES.put(EntityType.SILVERFISH, new String[]{"Scurry McScuttle", "Sneaky McBugface", "Squirmy", "Wigglepuff", "Flitter", "Shiny McCrawl", "Slippy", "Creepy McCreep", "Squeegee", "Bugsy", "Wiggleworm", "Nibbles", "Chitterbug", "Squiggles", "Glitterbug", "Tiny McCrawl", "Crawly McSilver", "Flicker", "Scuttles", "Fuzzbug", "Glitterpuff", "Creeperoni", "Slitherbug", "Buzzy", "Shiny Pests"});
        MOB_NAMES.put(EntityType.SKELETON, new String[]{"Boney McBang", "Sir Rattlebones", "Skeletor", "Bonehead", "Rattle McRattle", "Skelly McChomp", "Bonesaw", "Rattlepop", "Mr. Skelly", "Grim McRattle", "Spooky McBoney", "Bonecrusher", "Skellypants", "Jiggles", "Bone Daddy", "Boney McBang", "Grim Grin", "Spindly McRattle", "Tibia", "Bony McBoneface", "Skelefun", "Snapper", "Rattlemaster", "The Bone Ranger", "Pops", "Sans", "Papyrus"});
        MOB_NAMES.put(EntityType.SKELETON_HORSE, new String[]{"Bone Digger", "Rattle Gallop", "Neigh-bleed", "Sir Rides-a-lot", "Trots McRattle", "Hoofington", "Grim Galloper", "Rattlehoof", "Bones McCanter", "Gallops McGrim", "Skeletal Steed", "Bone Pony", "Whinnypants", "Boney Hoofster", "Spooky Saddle", "Mr. Bonehoof", "Clop Clop", "Sir Bones-a-lot", "The Galloping Grave", "Neighing Bones", "Trotterino", "Whisperhoof", "The Bone Charger", "Cloppy McRattle"});
        MOB_NAMES.put(EntityType.SLIME, new String[]{"Squishy McSquish", "Jelly McBounce", "Blobber", "Gooey McWobble", "Bouncy McSlime", "Splat", "Squishster", "Jellybean", "Goopster", "Blobby McBounce", "Slurp", "Wobbles", "Squidge", "Flubber", "Squishzilla", "Jellypuff", "Slammy", "Gloop", "Wobblebutt", "Squishypants", "Slimetastic", "Bloop", "Bouncy Blob", "Gooey McGloop", "Wobblemeister"});
        MOB_NAMES.put(EntityType.SNOW_GOLEM, new String[]{"Frosty McChill", "Snowballer", "Chilly McFlake", "Flurry McFrost", "Snowmanator", "Igloohead", "Frostbite", "Fluffypants", "Mr. Snowy", "Snowplow", "Chillington", "Iceman", "Frozen Fluff", "Blizzard Buddy", "Frosty the Not-So-Dead", "Snow Snoozer", "Icicle Pete", "Winter Wobble", "Flurrypuff", "Brrr", "Snowman McChomp", "Snowy McFluffster", "Melted McMelt", "Puffy McFreeze", "Frostface"});
        MOB_NAMES.put(EntityType.SPIDER, new String[]{"Webster", "Spidey McCrawl", "Tanglepaws", "Creepy McCrawl", "Fuzzy McSpin", "Spindle", "Sir Web-a-lot", "Sticky McLegs", "Spooky McTangles", "Arachnobuddy", "Leggy", "Webinator", "Creepersnare", "Chompers", "Fluffy McCrawl", "Stickywiggle", "Spinnerella", "Crawlster", "Webster the Web", "Squigglypaws", "Bitey McTangle", "Legzilla", "Spideypoof", "Lurky", "Spider-Man"});
        MOB_NAMES.put(EntityType.SQUID, new String[]{"Inky McSquirt", "Squishy McTentacle", "Squeebles", "Inkster", "Tentacle-Tastic", "Squirty McInkface", "Splashy", "Sir Ink-a-lot", "Squelchy", "Inkblob", "Wobbles", "Squidney", "Tentacool", "Squeeze", "Squidly", "Inkblot", "Squidward", "Wigglebeak", "Squishmonster", "Inky Doodle", "Tentacle Trouble", "Slurpy", "Inkify", "Splash Squid"});
        MOB_NAMES.put(EntityType.STRAY, new String[]{"Frosty McPaws", "Sir Snowflake", "Chillington", "Paws McFluff", "Snowy McSniff", "Woofy", "Brrr-ito", "Frostbite", "Pupperoni", "The Cold Pup", "Chilly McBark", "Fluffernutter", "Icy Woof", "Snowstorm", "Cold Nose", "Shiverpaws", "Pawprint", "Snoozer", "Frostwoof", "Fluffypaws", "Winter Woof", "Chompers", "Flurrypup", "Snowy Snuggles"});
        MOB_NAMES.put(EntityType.TROPICAL_FISH, new String[]{"Finny McSplash", "Bubblebutt", "Swimmy McColor", "Tropi-Call Me", "Gilligan", "Flipperoni", "Splashington", "Coralina", "Wiggles", "Bubbles McFish", "Fishy McFins", "Aquafizz", "Swimmy Pops", "Neon McFlare", "Tropi-Twist", "Finnigan", "Blubbers", "Fins McGlitter", "Splashy McFishface", "Gilly McGlow", "Tropicana", "Finster", "Puffy McSwim", "Watermelon Finn"});
        MOB_NAMES.put(EntityType.TURTLE, new String[]{"Shellby", "Turtley McTurtleface", "Squirtle", "Slowpoke", "Flippers", "Shelldon", "Turtleneck", "Bubbles", "Mr. Snappy", "Waddles", "Turtle Power", "Crawlster", "Turtly McChill", "Shellshock", "Turtleino", "Snappy McShell", "Flicker", "Sir Crawls-a-lot", "Turtletastic", "Pebbles", "Shellington", "Turtleneck Ted", "Wiggleflap", "Cuddlepaws", "Sandy"});
        MOB_NAMES.put(EntityType.VEX, new String[]{"Flitty McGrumpy", "Whiskerflap", "Mini McMischief", "Buzzypants", "Vexter", "Zippy", "Pesty McFloat", "Grumpy Wings", "Twirly", "Swoopy", "Tiny McVexy", "Flutterbutt", "Whizzy", "Annoyance", "Vexy McVexface", "Pesteroni", "Mischief Maker", "Flapzilla", "Squeaky", "Vexinator", "Whirly", "Wingy McBother", "Fluttergrump", "Whizzlebuzz"});
        MOB_NAMES.put(EntityType.VILLAGER, new String[]{"Bob the Builder", "Farmer Joe", "Trader McTalk", "Wanderin' Willie", "Granny McGrumble", "Chatterbox", "Barry the Blacksmith", "Villager Vibes", "Mister Mustache", "Bargain Bill", "Cabbage Carl", "Woolly Walter", "Grumpy Greg", "Peddler Pete", "Professor Plop", "Old Man Jenkins", "Wally the Farmer", "Haggler Hank", "Mayor McTalky", "Lumberjack Larry", "Penny the Peddler", "Bobby the Baker", "Crafty Carl", "Farmville Fred"});
        MOB_NAMES.put(EntityType.VINDICATOR, new String[]{"Choppy McChop", "Axey McSwing", "Vindicator Vibes", "Razor McRage", "Smashy", "Choppy McAxeface", "Vindi McVex", "Swingy McSmash", "Sir Slashes-a-lot", "Vindi McRage", "Axe-Tastic", "Whacko", "Grumpy McChop", "Slashington", "Berserker Bob", "Axey McRage", "Slice 'n' Dice", "Smashster", "Slashy McSwing", "Ragey McRageface", "Lumberjack Larry", "Axeholic", "Chopzilla", "Vindi-Vibes"});
        MOB_NAMES.put(EntityType.WITCH, new String[]{"Hexy McPotion", "Brewster", "Spelly McBrew", "Warty McWitchface", "Cackle Queen", "Potion Poppy", "Bubbles the Brewster", "Witchy Poo", "Funky Brewster", "Hexy McFlask", "Cauldron Carla", "Potion Polly", "Wicked Wanda", "Broomstick Betty", "Spellster", "Warty McWobbles", "Brewed Awakening", "Cackle McPotion", "Witchypoo", "Cauldronina", "Bubbling Betty", "The Wicked Whisk", "Potionator", "Broomy McFly", "Wigglewitch"});
        MOB_NAMES.put(EntityType.WITHER_SKELETON, new String[]{"Bone Crusher", "Skelly McSpooky", "Wither McChill", "Rattlebones", "Boney McBoom", "Skellybones", "Witherface", "Skele-fury", "Bonehead", "Grim Rattle", "Spooky McBones", "Scary McWither", "Tusk McChomp", "Wobbles the Wither", "Skullcrusher", "Bonezilla", "Wither McClash", "Rattlepaws", "Boney McBlast", "Scaley McRattle", "Grim Reaper", "Creepy McBone", "Boomy McSkelly", "Wither-Whack"});
        MOB_NAMES.put(EntityType.WOLF, new String[]{"Howly McBark", "Woofy McSniff", "Barkington", "Fluffy McWoof", "Paw-some", "Furball", "Barky McChomp", "Sniffles", "Woofington", "Growler", "Sir Sniff-a-lot", "Wagster", "Fur-tastic", "Barky", "Puppy McHowl", "Woofzilla", "Snouty McBark", "Howler", "Furball McGrowl", "Wolfy McWolfface", "Paw-sitive Vibes", "Wags", "Tails McFluff", "Sniff-a-lot"});
        MOB_NAMES.put(EntityType.ZOMBIE, new String[]{"Zombo", "Bitey McGroan", "Grumblepants", "Zombinator", "Brains McBite", "Grouchy Gus", "Shamble McStumble", "Groany McZombie", "Blinky", "Zombuddy", "Slouchy McScratch", "Brainy", "Stumbles", "Groaner McGrouch", "Zombiefied", "Grim Grunter", "Mumble", "Stinky McBrain", "Grumble Guts", "Mr. Groan", "Shamblor", "Rotty McShamble", "Zomboni", "Biter McGrouch", "Undead Andy"});
        MOB_NAMES.put(EntityType.ZOMBIE_HORSE, new String[]{"Grim Galloper", "Rotty McHoof", "Undead Steed", "Neigh-biter", "Gallopzilla", "Zombino", "Stumbler", "Boney Hooves", "Creepy Canter", "Moulder", "Shamble Hoof", "Ghoul Gallop", "Rider of the Undead", "Clop 'n' Groan", "Rotten Rider", "Neigh-zombie", "Boney Galloper", "The Undead Trotter", "Grim Hoof", "Creepy McClop", "Clopzilla", "Spooky Saddle", "Ghoulhoof", "Neighing Nightmare"});
        MOB_NAMES.put(EntityType.ZOMBIE_VILLAGER, new String[]{"Grumpy McTrade", "Bitey McBargain", "Mumbling Merchant", "Zombarb", "Brains for Sale", "Zom-Bob", "Trader McGrumble", "Rotty McDeal", "Bargain Bob", "Zombino", "Snoozy Sam", "Shamble Salesman", "Grumblegoods", "Vince the Villager", "Trader the Undead", "Zombart", "Brainy McBarter", "Rotty McBargain", "Mister Mumble", "Undead Vendor", "Shopper McScratch", "Zombie Dickering", "Grumble Deals", "Undead Merchant"});
        MOB_NAMES.put(EntityType.WARDEN, new String[]{"Grumble McGrowl", "Blinky McBoom", "Gloominator", "Grumblepuff", "Whispertron", "Deep Snarl", "Thuddington", "Rumblepaws", "Echo McGrumble", "Stompy McStare", "Groan Machine", "Sniffles", "Darkness Walker", "Thudster", "Beneath-the-Boom", "Deep Digger", "Gloomy McRumble", "Shadow Sniffer", "Big Gloom", "Earthshaker", "Big Grumble", "Sonic Boom", "Wobblecrusher", "Bassy McGrowl"});
        MOB_NAMES.put(EntityType.WITHER, new String[]{"Lord Doomfist the Decimator of Hope, Supreme Ruler of Destruction and Unofficial Master of Blowing Things Up", "Baron Blackskull, the Withering Wielder of Triple Chaos, and Purveyor of Explosive Disasters", "The Eternal, Unstoppable Wither King of the Unseen Depths, Destroyer of Life and Regularly Annoyed by Skeletons", "Count Obsidian the Malevolent, Bringer of Witherous Woes and Lord of the Endless Skyward Explosions", "Sir Wibblebones, the Defiler of Worlds, Shaker of Foundations, and Collector of Overrated Potions", "The Blightmaster, Scourge of the Underworld, Unleasher of Withering Wrath and Inveterate Aficionado of TNT", "Grimfury the Eternal, Ender’s Worst Nightmare and Bane of All Things Cute and Fluffy", "Wibberton the Unstoppable, Conqueror of Realms and Professional Ruiner of Entire Landscapes", "Overlord Splinterbone, Destroyer of Everything, and Impressive Collector of Unnecessary Wither Skulls", "The Unholy Triad of Doom, Dark Lord of the Witherworld and Chronic Exploder of Everything within Reach"});
        MOB_NAMES.put(EntityType.WANDERING_TRADER, new String[]{"Nomad McDeal", "Trader Joe", "Wanderin' Willie", "Barter Bob", "Roving Ralph", "Haggling Harry", "Drifty McTrade", "Peddler Pete", "Bargain Benny", "Wanderlust Wayne", "Sale McSnail", "Mister Wander", "Driftin' Dan", "Nomadic Ned", "Peddler Patty", "Wobbletrade", "Roamy McBargain", "Shifty McTrader", "Roving Roy", "Haggler Hank", "Rolling Rick", "Swapmaster", "Vagabond Vince", "Wanderin' Wendy"});
       
        // Add more mob types and names as needed
    }
}
